site_name: TaskFlow Docs
theme: material
nav:
  - Inicio: index.md
  - Configuraci贸n del Entorno: entorno.md
  - Configuraci贸n de la Base de Datos: base_datos.md
  - Autenticaci贸n: autenticacion.md
  - Vistas y URLs: vistas_urls.md
  - Formularios y Plantillas: formularios_plantillas.md
  - Gesti贸n de Proyectos: proyectos.md
  - Errores y Soluciones: errores.md
  - Notificaciones: notificaciones.md  
theme: readthedocs